### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by dmvdbrugge** [mollie/api-documentation#103]
The readme specifies MIT license, but there is no accompanying LICENSE(.md) file.

**Comment by willemstuursma** [comment]
I guess for documentation, CC BY-SA 3.0 would be better. This is the license also used by StackOverflow for it's content.

https://creativecommons.org/licenses/by-sa/3.0/ 

@mollierobbert ?

**Comment by willemstuursma** [comment]
CC BY-SA 4.0 has been added, thanks for reporting @dmvdbrugge.

**Comment by dmvdbrugge** [comment]
The readme still says it's MIT 😉

**Comment by willemstuursma** [comment]
Thanks Dave
