### ISSUE TITLE
Create guide on Mollie's maximum throughput

### ISSUE THREAD

**Issue by willemstuursma** [mollie/api-documentation#120]
We should have a guide that will explain how much throughput we can process (in general terms), referring to our ticketing platform customers, maybe pointing out some of the events.

There should also be some kind of warning that doing your own stress-test against our platform will get you banned, and a warning to contact your account manager if you expect very high payment peak volumes so that the various limits can be set correctly.

**Comment by mollierobbert** [comment]
I'm not sure if we should name numbers, since our max. throughput will keep increasing over time as the engine improves.
