### ISSUE TITLE
Mollie-api-php examples

### ISSUE THREAD

**Issue by sandervanhooft** [mollie/api-documentation#124]
As discussed [here](https://github.com/mollie/mollie-api-php/issues/217) I am going to add some examples for the Mollie-api-php client.

**Comment by sandervanhooft** [comment]
@willemstuursma Where should the php code samples go?

It seems like the curl examples are not kept in this repo's source files ([example](https://github.com/mollie/api-documentation/blob/5109e1cf818db4827e89de4c8cbd788e27ae5994/source/reference/v2/payments-api/create-payment.rst#request)).

**Comment by sandervanhooft** [comment]
Nvm... They are only visible in RAW mode.

**Comment by sandervanhooft** [comment]
I'll put them below the curl examples. Let me know if I should wrap them or something.

**Comment by sandervanhooft** [comment]
This is what it would look like:

```
Example
-------

Request
^^^^^^^
.. code-block:: bash
   :linenos:

   curl -X POST https://api.mollie.com/v2/payments \
       -H "Authorization: Bearer test_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM" \
       -d "amount[currency]=EUR" \
       -d "amount[value]=10.00" \
       -d "description=My first payment" \
       -d "redirectUrl=https://webshop.example.org/order/12345/" \
       -d "webhookUrl=https://webshop.example.org/payments/webhook/" \
       -d "metadata={\"order_id\": \"12345\"}"

.. code-block:: php
   :linenos:

    $mollie = new \Mollie\Api\MollieApiClient();
    $mollie->setApiKey("test_dHar4XY7LxsDOtmnkVtjNVWXLSlXsM");
    $payment = $mollie->payments->create([
      "amount" => [
          "currency" => "EUR",
          "value" => "10.00" // You must send the correct number of decimals, thus we enforce the use of strings
      ],
      "description" => "My first payment",
      "redirectUrl" => "https://webshop.example.org/order/12345/",
      "webhookUrl" => "https://webshop.example.org/payments/webhook/",
      "metadata" => [
          "order_id" => "12345",
      ],
    ]);
```

**Comment by sandervanhooft** [comment]
I'll leave the response examples untouched

**Comment by willemstuursma** [comment]
@vernondegoede can we work with this?

**Comment by sandervanhooft** [comment]
@willemstuursma @vernondegoede Gentle reminder :)

I'd like to update the docs with PHP client examples, preferably in the coming weeks - let me know in what format to contribute.

**Comment by willemstuursma** [comment]
You can create a PR on this repository @sandervanhooft.

Tip: to quickly check changes in `.rst` files, use `make html-only`.

**Comment by sandervanhooft** [comment]
Thanks @willemstuursma . Unfortunately I am facing issues installing it locally. Will open a separate ticket for that.

**Comment by willemstuursma** [comment]
#134

**Comment by willemstuursma** [comment]
#136

**Comment by sandervanhooft** [comment]
Just sent in PR #141.

**Comment by sandervanhooft** [comment]
I've documented as much as possible using the php client examples, tests and source.

Really nice to dive deeper into the client's inner working this way :).

There are a few examples I had to skip for now:

- **Refunds** GET (payment->getRefund('id') missing); CANCEL depends on GET
- **Chargebacks** (not found in client)
- **Mollie Connect** : TOKEN (requires OAuth provider example)
- **Settlements**: refunds, payments, chargebacks (which are endpoint aliases, no methods in client available). I can include the direct, non-aliased examples if this helps.
- **Permissions** (not found in client)
- **Organizations** (not found in client)

Also, I've left the "Guides" section out of scope. In the future it may be helpful to have php examples here as well.

Let me know how/if I can help with these remaining items or the guides.

**Comment by sandervanhooft** [comment]
Refund GET and CANCEL can be documented when [this PR](https://github.com/mollie/mollie-api-php/pull/242) has been merged on the php client.

**Comment by sandervanhooft** [comment]
I'm keeping this issue open for the upcoming Orders and Shipments php examples.

**Comment by sandervanhooft** [comment]
Hi @vernondegoede I'll add the Captures examples today and then this issue can be closed.

**Comment by sandervanhooft** [comment]
I need to check some things before closing this issue. Starting point:

https://github.com/mollie/api-documentation/issues/124#issuecomment-409650012

**Comment by sandervanhooft** [comment]
- [x] **Refunds** GET (payment->getRefund('id') missing); CANCEL depends on GET
- [ ] **Chargebacks** ~~Not found in client~~ On Payment resource. GET does not exist yet
- [ ] **Mollie Connect** : TOKEN (requires OAuth provider example)
- [ ] **Settlements**: refunds, payments, chargebacks (which are endpoint aliases, no methods in client available). I can include the direct, non-aliased examples if this helps.

- [ ] **Permissions** (not found in client)
- [ ] **Organizations** (not found in client)

**Comment by willemstuursma** [comment]
For now it is fine to me. I would like to have permissions and organizations in the client too. 

We'll be adding some new endpoints for partners soon.

**Comment by sandervanhooft** [comment]
> We'll be adding some new endpoints for partners soon.

@willemstuursma Can I read up on this somewhere? Preferably a summary

**Comment by willemstuursma** [comment]
@sandervanhooft anything remaining for this?

**Comment by sandervanhooft** [comment]
@willemstuursma I think we're ok for now 😄 . So I'll close this issue.
