### ISSUE TITLE
API and API version should be in document title

### ISSUE THREAD

**Issue by willemstuursma** [mollie/api-documentation#127]
So that I can distinguish the API versions in the Google search results: 
![screen shot 2018-07-18 at 16 30 48](https://user-images.githubusercontent.com/701299/42888194-fdcd410e-8aa7-11e8-9644-46213d689e2e.png)

**Comment by willemstuursma** [comment]
@vernondegoede  could you give this a little nudge if you have some time to spare?

**Comment by willemstuursma** [comment]
@vernondegoede could you help @MollieRick figure this out?

**Comment by MollieRick** [comment]
Fixed in #200
