### ISSUE TITLE
Move code example to top of the page?

### ISSUE THREAD

**Issue by mattijsbliek** [mollie/api-documentation#131]
At the moment you have to scroll through long lists of parameters before actually seeing what a request looks like. I propose we flip this and start with the example. If a parameter is not clear, you can read on and find out what it does.

Opinions @mollierobbert @willemstuursma?

**Comment by mollierobbert** [comment]
Could be nice. What about moving the example to a sidebar on the right? That's a common approach.

**Comment by mattijsbliek** [comment]
That would work, but only if your display is wide enough. Also, we would have to get rid of the max-width that’s currently on the container. Super quick devtools sketch:

![image](https://user-images.githubusercontent.com/2960795/43007053-8a7cbf54-8c37-11e8-81c3-b3205ba89581.png)

**Comment by mollierobbert** [comment]
Right. Might be too much of a hassle since it would only work for specific devices.

**Comment by sandervanhooft** [comment]
> At the moment you have to scroll through long lists of parameters before actually seeing what a request looks like. I propose we flip this and start with the example. If a parameter is not clear, you can read on and find out what it does.

@mattijsbliek I'd love this! But perhaps implement a "language switch" first?

**Comment by sandervanhooft** [comment]
(See #130)
