### ISSUE TITLE
Add payment method switcher to Payments API docs

### ISSUE THREAD

**Issue by mollierobbert** [mollie/api-documentation#132]
The documentation for the Payments API is huge - we have special parameters for almost every payment method.

We should fold all these payment method subheaders into a single switcher, like we used to have on the old docs.

**Comment by mollierobbert** [comment]
Referring to: https://docs.mollie.com/reference/v2/payments-api/create-payment#payment-method-specific-parameters

**Comment by vernondegoede** [comment]
@georgemaine Can we come up with a simple design for this? Maybe a basic tab bar would suffice.

**Comment by mollierobbert** [comment]
We had a basic tab bar in the past, but it grew too big, hence we replaced it with a dropdown.

(I do still think a tab bar makes more sense in terms of proper UI.)

**Comment by mollierobbert** [comment]
Thanks for your suggestion, George. This is not what we're looking for though. @vernondegoede perhaps you can sit with George to elaborate what we need?

**Comment by vernondegoede** [comment]
@mollierobbert Will do :+1:

**Comment by willemstuursma** [comment]
@georgemaine's idea looks like a nice addition none the less.

**Comment by vernondegoede** [comment]
We decided to re-use the tabs that we use within Dashboard.

**Comment by MollieRick** [comment]
This is done

**Comment by vernondegoede** [comment]
This is not done yet :)

The goal of this was to split up the specific parameters for each payment method in this section: https://docs.mollie.com/reference/v2/payments-api/create-payment#payment-method-specific-parameters.

We're currently using a very long list of parameters for each payment method, which isn't really user friendly.

**Comment by MollieRick** [comment]
Whoops, sorry :-)

**Comment by albert-carreras** [comment]
This feature is now live 👍

**Comment by mollierobbert** [comment]
Well done Albert!
