### ISSUE TITLE
Rethink our guides structure

### ISSUE THREAD

**Issue by mattijsbliek** [mollie/api-documentation#146]
When I want to start using Mollie, I want a clear step-by-step guide I can follow along with. At the moment we offer no such thing. There is no index page for our guides, and they’re all on the same hierarchical level.

I think in essence we have three main topics:

* Payments
* Recurring
* Connect

All these should have a proper follow along guide which you can follow. Existing Connect has one, but it’s much too high level.

Next to that we have a few guides which fall under "Basic information", and are applicable across Mollie. I’m thinking of authentication, security, error handling etc. Some of these are nice to know upfront, such as authentication because you need that regardless. Others should be available when you need them.

So in short, I think it would be really good for guides to:

* Have a proper landing page which highlights the most common guides.
* Not show every guide in the sidebar, but split it up per API (e.g. Payments, Recurring, Connect).
* Make sure that you can follow along to the guides, and at the end have a working application.
* Make the guides clearly scannable.
* Not muddle the waters by putting popular pages such as integrating payments on the same level as rarely used ones such as QR codes.

This should be a team effort because it involves extracting knowledge from all team, copy writing, design, and development. I realise this is not an overnight issue, but it would be good to start getting the guides up to par with the API reference.

**Comment by mollierobbert** [comment]
The following PR will introduce better top-level navigation, as a first big step towards the structure you are suggesting — https://github.com/mollie/api-documentation/pull/765

**Comment by mollierobbert** [comment]
#765 was merged. Closing this issue.
