### ISSUE TITLE
Write a proper getting started for Payments

### ISSUE THREAD

**Issue by mattijsbliek** [mollie/api-documentation#147]
Our payments guide is lacking pretty severely at the moment. It does not offer any help in how to actually create payments. Our API clients are not mentioned, and it does not contain API examples. It stops at a high level overview of how Mollie Payments work.

We should really rethink this, and create and easy to follow guide of how to get set up. Ease of use is always a priority for us, and at the moment we’re not living up to our own standards here.

**Comment by sandervanhooft** [comment]
@mattijsbliek 

What target audience is this guide for? Developers or merchants?

Is there any information available what decisions they struggle with / what Mollie has advised in the past?
