### ISSUE TITLE
Add redirects using AWS Lambda

### ISSUE THREAD

**Issue by vernondegoede** [mollie/api-documentation#190]
Following files need to be redirects using serverless functions in AWS Lambda:

```
source/migrating-v1-to-v2.rst => source/payments/migrating-v1-to-v2.rst
source/guides/multicurrency.rst => source/payments/multicurrency.rst
source/guides/recurring.rst => source/payments/recurring.rst
source/guides/payment-status-changes.rst => source/payments/status-changes.rst (folder + filename aangepast)
source/payments/webhooks.rst => source/guides/webhooks.rst
source/security.rst  => source/guides/security.rst
```

While we're at it, we should probably also redirect top level routes:
```
reference/v2 => reference/v2/payments-api/create-payment
reference/v1 => reference/v1/payments-api/create-payment
```

**Comment by willemstuursma** [comment]
Can it be brought under VCS in this repository?

**Comment by vernondegoede** [comment]
Yes, they're basically small JS functions.

**Comment by willemstuursma** [comment]
Great! They should also be auto deployed from the travis scripts.

**Comment by vernondegoede** [comment]
Related: #54.

**Comment by willemstuursma** [comment]
Cant we do this via 
https://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html

It can probably be done via the command line client. It seems less involved than using serverless.

**Comment by willemstuursma** [comment]
It seems possible if we configure Cloudfront to use the website name of the S3 bucket?

https://stackoverflow.com/questions/22740084/amazon-s3-redirect-and-cloudfront

@wvdeutekom can you confirm that we are using the `${bucket_name}.s3-website.${region}.amazonaws.com` in Cloudfront?

**Comment by vernondegoede** [comment]
Wijnand is on holiday. @hvalle could you take a look?

**Comment by hvalle** [comment]
Do we need a redirect or can we copy these resources to the path where we need them?

**Comment by martijnpolder** [comment]
Our S3 buckets are only accessible through CloudFront, which sanitizes and enriches the response headers a bit using Lambda. 
For this reason we can't use S3 based tricks, but instead were planning on using a Lambda function as well, like in the example Homero dug up. As we're using Lambda already, a lot of this in in place.
