### ISSUE TITLE
Subscription vs recurring payments confusion

### ISSUE THREAD

**Issue by sandervanhooft** [mollie/api-documentation#195]
While working on Laravel Cashier, I notice that the distinction between **Subscriptions** and **Recurring Payments** is not clear.

I am not sure when to choose what, and what the limitations/consequences will be, both short term and long term. When talking to Mollie representatives, I get a different response each time.

Perhaps this can be clarified further in the docs?

At the moment, I am not entirely sure what Subscriptions really offer on top of Recurring Payments.

A few things I noticed:
- subscription can be updated, payment not
- subscriptions offer nice separate dashboard features, so it's easy to see what revenue is recurring
- subscriptions do not offer metadata
- payment offers metadata, but I'm not sure it carries over to subsequent payments
- I'm not sure what happens when Mollie decides to cancel a subscription (webhook?) i.e. after a customer complaint
- retrieving past subscription's payments is complex right now (it's on backlog)
- getting upcoming "payment date" is impossible right now for both payment and subscription (it's on backlog for subscription)

**Comment by willemstuursma** [comment]
#201

**Comment by willemstuursma** [comment]
Quoting @MollieRick: 

> Maybe it's nice to have a little table with the limitations and differences between On-demand and Subscriptions.
