### ISSUE TITLE
Dead Hyperlink

### ISSUE THREAD

**Issue by HugoPrinse** [mollie/api-documentation#207]
https://docs.mollie.com/#

If possible it would be wise to leave communication at this level to our ready-made **Clients.** This allows you to still be in control without reinventing the wheel.

Issue  = Clients is a hyperlink that should go to integrations but leads back to the same page

**Comment by Smitsel** [comment]
It was intended to go to:
https://docs.mollie.com/index#clients-modules-and-plugins

So it's not quite dead ;)
