### ISSUE TITLE
Get Organization documentation is unclear

### ISSUE THREAD

**Issue by willemstuursma** [mollie/api-documentation#212]
The documentation does not describe when you can access an organization, not how you should set up the authentication.

**Comment by sandervanhooft** [comment]
Also, there's a reference to `LIST organizations` call, but there's no documentation for this.

**Comment by willemstuursma** [comment]
Its coming next week @sandervanhooft

**Comment by MollieRick** [comment]
@sandervanhooft The `LIST organization` call is now available.

**Comment by sandervanhooft** [comment]
Thanks @willemstuursma and @MollieRick ! I’ll implement it in the php client.

**Comment by sandervanhooft** [comment]
https://github.com/mollie/mollie-api-php/pull/274

**Comment by MollieRick** [comment]
Thanks @sandervanhooft !
