### ISSUE TITLE
/reference/v2 redirect instead of 404 (minor)

### ISSUE THREAD

**Issue by sandervanhooft** [mollie/api-documentation#226]
I was just bookmarking the API reference, noticed that [/reference/v2/](https://docs.mollie.com/reference/v2/) currently gives a 404. I think it would be better if it redirects to [/reference/v2/payments-api/create-payment](https://docs.mollie.com/reference/v2/payments-api/create-payment).

Same for [/reference/](https://docs.mollie.com/reference/) pointing to the latest version, currently [/reference/v2](https://docs.mollie.com/reference/v2/).

**Comment by vernondegoede** [comment]
Will be picked up with #190.
