### ISSUE TITLE
No checkouturl available after failed payment?

### ISSUE THREAD

**Issue by haayman** [mollie/api-documentation#228]
After the payment has failed I want to offer the client a new change to pay, but Payment->getCheckoutUrl is empty?

Am I wrong when I assume this URL should be available as long as the payment isn't paid?

**Comment by sandervanhooft** [comment]
First: this seems to relate to the php example. Right?

In that case, it's about this function [here](https://github.com/mollie/mollie-api-php/blob/b31e57023e90667d27e813a7253e023763331042/src/Resources/Payment.php#L320). As you can see it only returns a checkoutUrl if it's available on the API JSON response.

To me it makes sense that the `checkoutUrl` is not always available. It should not be available if the payment should not be checked out to complete. (I'm not sure this is the case though.)

I.e. no checkoutUrl for:
- Subscription payments as these do not require a checkout.
- Payments with a end-state, like 'canceled', 'failed', 'completed', 'expired' (probably anything but `open`). [More about states here](https://docs.mollie.com/payments/status-changes).

For retrying a `failed` payment you'd need to create a new payment.

**Comment by haayman** [comment]
Thanks, this is clear.
Am I right in thinking that in the previous version we could retry a failed
payment?

Op di 18 sep. 2018 16:16 schreef Sander van Hooft <notifications@github.com

**Comment by sandervanhooft** [comment]
Don't know 😄

**Comment by willemstuursma** [comment]
@haayman if a payment has failed, the status is final and can no longer be changed. This was the same in the v1 version. 

For v1 and v2, you can create a payment without a method. The shopper can then retry payments until one succeeds (or he/she gives up) at which point in time you will receive the status via the webhook.

The upcoming Orders API will allow you to create new Payments against an Order.
