### ISSUE TITLE
OAuth/Connect label (or header)

### ISSUE THREAD

**Issue by sandervanhooft** [mollie/api-documentation#249]
In the reference section, I suggest to add a "OAuth only" label above the Connect navigation item.

These items are already grouped using spacing, but it's not really clear why currently.

**Comment by MollieRick** [comment]
Maybe also a "Partner only"-label, cause we're heading more and more over.
![screen shot 2018-11-12 at 14 40 44](https://user-images.githubusercontent.com/42934521/48350934-f549df00-e688-11e8-8c28-d9a72fdbb658.png)

**Comment by willemstuursma** [comment]
We now have Organization Access Tokens too, making these endpoints more available to merchants.

**Comment by mollierobbert** [comment]
Thanks for raising this, Sander! We are restructuring the docs in #146. I think those changes will sufficiently separate Mollie Connect from our Payments product. Closing this issue for now.
