### ISSUE TITLE
Klarna rejects Order update example response

### ISSUE THREAD

**Issue by sandervanhooft** [mollie/api-documentation#282]
[The update order docs](https://docs.mollie.com/reference/v2/orders-api/update-order) mention this at the page head:

> When updating an order that uses a pay after delivery method such as Klarna Pay later, it can be the case that Klarna does not accept the requested changes. In that case the order is still valid, though the requested changes have not been applied to the order.

It's not clear to me what response to expect when this happens. A 20x, or an error?

**Comment by Smitsel** [comment]
422 UnprocessableEntityException with message "Order ord_xxxxx cannot be updated: Klarna does not accept the new adress(es)."

**Comment by sandervanhooft** [comment]
Perhaps like this?

> When updating an order that uses a pay after delivery method such as Klarna Pay later, it can be the case that Klarna does not accept the requested changes**, resulting in an error response**. In that case the order is still valid, though the requested changes have not been applied to the order.

**Comment by Smitsel** [comment]
Yes i like it. But minus the ** right?

**Comment by sandervanhooft** [comment]
Polished it a bit more. How about this? @Smitsel 

> When updating an order that uses a *pay after delivery* method such as *Klarna Pay later*,
Klarna may decline the requested changes, resulting in an error response from the Mollie API.
The order remains intact, though the requested changes are not persisted.

**Comment by sandervanhooft** [comment]
I'll prep the PR for you if you're ok with this.

**Comment by Smitsel** [comment]
Yes please ! 👍
