### ISSUE TITLE
Further clarify webhooks / statuses

### ISSUE THREAD

**Issue by sandervanhooft** [mollie/api-documentation#300]
While working on default webhooks for Laravel-Mollie, I noticed that the webhook documentation confuses me.

I am trying to fire matching events for all possible webhook calls. (I.e. PaymentCanceled for payment status `canceled`).

**[Webhooks guide](https://docs.mollie.com/guides/webhooks)**:
_Payments_:
- refund and chargeback calls mentioned, but only a sidenote on the [payment status changes page](https://docs.mollie.com/payments/status-changes). If that note is correct, it's no longer possible to implement handling refunds/chargebacks in a stateless system (= system that does not track payments in db). I mean this note: "In the v1 API, there were statuses for when payments were refunded, charged back, or paid out (settled). These statuses have been removed in v2. You can get the same information from other properties on the Payment object."

_Orders_:
- "... the webhook will be called when: A shipment is created for the order." But in the order status changes page, I read this: `shipping`: "This is not a status Mollie will call your webhook for".
- no mention about refunds / refund webhook calls.

I'd love to read how to recognize a chargeback/refund "status update" from a "normal" status update. Not sure where the description should go.😄

**Comment by sandervanhooft** [comment]
@willemstuursma Is there a way to deduce with 100% certainty (no false positives) that a webhook was called for a payment refund / chargeback, _without having the payment persisted locally_? I.e. no flag in db that a refund was issued

**Comment by willemstuursma** [comment]
> Is there a way to deduce with 100% certainty (no false positives) that a webhook was called for a payment refund / chargeback, without having the payment persisted locally?

No.

**Comment by sandervanhooft** [comment]
Bummer 😄 .

I noticed the dedicated statuses for refunds/chargebacks were dropped in v2, and I understand why.

But this now introduces additional complexity in the client, which I think should be handled Mollie side. 

Not sure what a nice solution for that would be though...
- Adding extra information to webhook call would leak too much information.
- Adding `refund` / `chargeback` status to payment is a bad solution because a payment can be _partially_ refunded. (and that's probably why these are deprecated in v2)
- Optionally including history array in payment may be a nice one.
