### ISSUE TITLE
Add more info on retry schema for webhooks

### ISSUE THREAD

**Issue by fre-db** [mollie/api-documentation#336]
Currently the documentation on api-documentation/source/guides/webhooks.rst describes how the webhook will be called 10 times before you stop trying.

We received 8 failed calls and have now fixed the problem, however we do not know whether the webhook will still be called or when it will be called. Maybe adding the timing of the retry schema to the documentation could clarify this. 

The approx. interval between the calls was:
 1m - 1m - 1m - 6m - 6m - 6m - 6m

**Comment by MollieRick** [comment]
Relates to #300

**Comment by MollieRick** [comment]
We added the timeout intervals to the guide. Thanks for suggesting :-)
