### ISSUE TITLE
Remove Organization Access Tokens from v1-docs

### ISSUE THREAD

**Issue by MollieRick** [mollie/api-documentation#346]
In the v1-documentation the Organization Access Tokens are mentioned as a way of authentication, but they don't work in that version. They should be removed from the v1-docs.

**Comment by willemstuursma** [comment]
@mollierobbert can you advice?

**Comment by mollierobbert** [comment]
Rick is correct - we do not support OATs in v1. This is an error in the documentation.

**Comment by MollieRick** [comment]
It is removed.
