### ISSUE TITLE
php examples layout issues

### ISSUE THREAD

**Issue by sandervanhooft** [mollie/api-documentation#349]
Has something changed in the php examples source (parsing?) or styles?

The indentation is off, some odd spacing appears sometimes (but not consistently). Not sure what is causing this.

**Comment by sandervanhooft** [comment]
For example,

```php
<?php
$mollie = new \Mollie\Api\MollieApiClient();
$mollie->setAccessToken("access_Wwvu7egPcJLLJ9Kb7J632x8wJ2zMeJ");
$profile = $mollie->profiles->create([
"name" => "My website name",
"website" => "https://www.mywebsite.com",
"email" => "info@mywebsite.com",
"phone" => "+31208202070",
"categoryCode" => "5399",
"mode" => "live",
]);
```

was (and should be):

```php
<?php
$mollie = new \Mollie\Api\MollieApiClient();
$mollie->setAccessToken("access_Wwvu7egPcJLLJ9Kb7J632x8wJ2zMeJ");
$profile = $mollie->profiles->create([
    "name" => "My website name",
    "website" => "https://www.mywebsite.com",
    "email" => "info@mywebsite.com",
    "phone" => "+31208202070",
    "categoryCode" => "5399",
    "mode" => "live",
]);
```

**Comment by sandervanhooft** [comment]
<img width="442" alt="image" src="https://user-images.githubusercontent.com/7265703/49897242-ddb37100-fe55-11e8-9881-050422185d22.png">
Other example. Strange spacing between characters (surrounding arrows). [Source](https://docs.mollie.com/reference/v2/profiles-api/delete-profile#example)

**Comment by willemstuursma** [comment]
![screen shot 2018-12-13 at 09 49 14](https://user-images.githubusercontent.com/701299/49926661-61a04400-febc-11e8-91b0-0c67e8d31a29.png)

Looks fine to me. Try cmd+shift+r? (Ctrl+F5 on Windows)

**Comment by sandervanhooft** [comment]
Chrome: works fine.
Safari v12.0.2: after emptying cache, refresh, problem persists. Not sure what's happening.

**Comment by sandervanhooft** [comment]
(The indentation issue occurs in Chrome as well)

**Comment by albert-carreras** [comment]
This was due to some changes in the indentation for the language selector. Will look into it 👍

**Comment by albert-carreras** [comment]
This is now fixed.

**Comment by sandervanhooft** [comment]
🎉
