### ISSUE TITLE
webhook lacks example of postbody

### ISSUE THREAD

**Issue by jappeace** [mollie/api-documentation#362]
Just giving an example of the post call of the webhook in:
https://github.com/mollie/api-documentation/blob/master/source/guides/webhooks.rst

I was expecting the body to be json but it's just raw text, since the entire api is almost json having a rawtext should be docoumented.

**Comment by MollieRick** [comment]
Hi @jappeace,

We just posting the ID of the payment or order. So if you set the webhook url as `https://www.example.org/webhook` we will call: `POST https://www.example.org/webhook?id=tr_xxxx`

**Comment by willemstuursma** [comment]
@MollieRick I think we can add an example of the HTTP call, so with the headers and the post body. The body has the `application/x-www-form-urlencoded` content type.

**Comment by willemstuursma** [comment]
@markovska if you have some time, can you try to add an example HTTP request to the documentation?

**Comment by jappeace** [comment]
@MollieRick I already got it working, there was the content type issue too, servant is very strict. I was just expecting json since the entire api is json but this is x-www-form-urlencoded.

Once I understood that content type I could use the generic FromForm instance and put a newtype into the servant type (company name is set by myself):

```haskell
newtype PaymentID = PaymentID
  { un_id :: Text.Text
  } deriving (Show, Eq, Generic)

instance FromForm PaymentID

type PayWebhook
   = "pay" :> "webhook" :> Capture "company" CompanyName :> ReqBody '[FormUrlEncoded] PaymentID :> Post '[JSON] NoContent

```

**Comment by willemstuursma** [comment]
The example has been added, thanks for reporting @jappeace.
