### ISSUE TITLE
Resource  property missing from Chargeback response?

### ISSUE THREAD

**Issue by firstred** [mollie/api-documentation#373]
Could it be that the Chargeback response should not provide the `resource` property or is it just missing from the documentation?

If it should be added I wouldn't mind making a Pull Request.

https://docs.mollie.com/reference/v2/chargebacks-api/get-chargeback

**Comment by willemstuursma** [comment]
Thanks. Confirming it's present, but not documented correctly. 

It's correctly shown in the example though. 

Would be great if you could create a PR.

**Comment by firstred** [comment]
Thanks! I'm going to try to run the docs locally and will send a PR once everything is up and running. Let's see if I can still spin up Sphinx (it's been quite a while).

**Comment by firstred** [comment]
Fixed by https://github.com/mollie/api-documentation/pull/376
