### ISSUE TITLE
Get Order API - Embedded payment._links.documentation is omitted

### ISSUE THREAD

**Issue by firstred** [mollie/api-documentation#380]
While browsing the Get Orders page, I noticed that the on the Get Payment page the `_links.documentation` link is always added, but not when requesting embedded payments for the current order (`_embedded.payments[0]._links.documentation`). Is this correct behavior?

Both the Get Order response example and actual response omit the `documentation` link, but that is not documented on the Get Payment page.

Please let me know what the actual behavior should be so that I can update both the documentation and TypeScript definitions accordingly. Thanks in advance!

**Comment by firstred** [comment]
TypeScript points out a few more:
- `expiresAt` is required, but also omitted as an embedded payment property
- `details`, even though it's tied to a payment method, it is still required for every single one of them, is omitted as well

**Comment by firstred** [comment]
I can confirm the three fields (`_embedded.payments[0]._links.documentation`, `_embedded.payments[0].expiresAt` & `_embedded.payments[0].details`) are omitted in both the example response and actual API responses.

**Comment by willemstuursma** [comment]
@MollieRick can you set update any examples and documentation?

**Comment by MollieRick** [comment]
@firstred What example have you looked at for the payment fields?

**Comment by mollierobbert** [comment]
I'm assuming this solved by now, given the age of this issue and since we updated a lot of our Orders API examples over the years.
