### ISSUE TITLE
iDEAL QR Codes - How to request them with the Orders API?

### ISSUE THREAD

**Issue by firstred** [mollie/api-documentation#381]
I have been looking all over the documentation site to figure out if there is a way to retrieve iDEAL QR codes with the Orders API, but as of yet haven't been able to. Is there or should there be a way to retrieve iDEAL QR codes from the Orders API? (...or Bancontact & Bitcoin QR codes?).

**Comment by willemstuursma** [comment]
Sorry, we haven't gotten to integrating QR codes with orders. 

They need a different solution because orders can stay open for 28 days, so we need QR codes that stay valid for that whole time.

**Comment by firstred** [comment]
Thanks for the explanation! :+1:
