### ISSUE TITLE
Get Payment does not include the QR Code?

### ISSUE THREAD

**Issue by firstred** [mollie/api-documentation#386]
The Get Payment page makes it seem as if requesting an already existing payment (initialized with the `include=details.qrCode` param) would include the QR code, but once you have created a payment with a QR code, there is no way to retrieve it again from the API.

**Comment by willemstuursma** [comment]
Thanks, we'll pick it up.

**Comment by willemstuursma** [comment]
Thanks for reporting @firstred. A fix will be released today.

**Comment by firstred** [comment]
Thanks!

**Comment by TimBiesmans** [comment]
Still got this issue with the Bancontact QR code...
