### ISSUE TITLE
Add code samples for each API client to Pagination guide

### ISSUE THREAD

**Issue by vernondegoede** [mollie/api-documentation#410]
We would like to show code samples showing how the pagination works for our various API clients to [the Pagination guides](https://github.com/mollie/api-documentation/blob/master/source/guides/pagination.rst).

To do:
- Add example on how to navigate between pages using API client for:
  - [ ]   Node.js (@firstred)
  - [x]   PHP (@sandervanhooft)
  - [ ]   Python
  - [ ]   Ruby (@justincase)
- Remove pagination examples from code samples in API reference.

**Comment by sandervanhooft** [comment]
@willemstuursma Will do!

**Comment by sandervanhooft** [comment]
I've just PR'd the php v2 example, but it seems to be breaking the code block selector.

May be related to having multiple examples on one page with the same html ID tag (had that one before, not sure at what page/what the fix was).

Any help?
