### ISSUE TITLE
Dropdown for method specific parameters too hard to find

### ISSUE THREAD

**Issue by willemstuursma** [mollie/api-documentation#427]
It was reported on Twitter that the dropdown for method specific parameters is too hard to find. 

https://twitter.com/mark_hamstra/status/1102217058262106113

**Comment by vernondegoede** [comment]
Totally agree, ran into this problem as well.

@georgemaine Do you have any ideas on how to improve this? Maybe switch to tabs (just like we do for code examples)?

**Comment by georgemaine** [comment]
I can investigate for sure, but I'm 99% sure @Giel has something sweet in the works for our guides in his fresh redesign of the dev section. Do you want to tackle this now or wait for his new design to drop?

**Comment by georgemaine** [comment]
On a second note, if it's not to much labor then I'd recommend one of these two options:

View proposal
![canvas](https://user-images.githubusercontent.com/12780418/53880206-b2818d80-4010-11e9-8701-d54ac6806528.png)

Get assets

[files voor vernon.framerx.zip](https://github.com/mollie/api-documentation/files/2936123/files.voor.vernon.framerx.zip)

**Comment by vernondegoede** [comment]
Thanks! I'll make it happen

**Comment by mollierobbert** [comment]
I think this is solved now, especially with the new Mollie API documentation stack.
