### ISSUE TITLE
Clear distinction between query and body params

### ISSUE THREAD

**Issue by sandervanhooft** [mollie/api-documentation#439]
Right now I have to go through the (intro) description text to find out if a parameter should be passed via the request _body_ or via the request _query string_. It's a bit tedious and error-prone.

Can we apply a label or another visual aid to quickly identify how a parameter should be passed?

Btw, right now the consensus seems to be "body parameter, unless stated otherwise".

**Comment by sandervanhooft** [comment]
My best guess this one is for @vernondegoede ?

**Comment by mollierobbert** [comment]
This is solved now with the new documentation stack.
