### ISSUE TITLE
White-labeling guide

### ISSUE THREAD

**Issue by sandervanhooft** [mollie/api-documentation#440]
The docs mention that it's possible to whitelabel Mollie's services, but it's not clear how.

I think the elements can be found in the docs, but it's fragmented, while the use case itself is very promising.

**Comment by willemstuursma** [comment]
You mean, integrating the checkout as much as possible in your own checkout, without using Mollie's hosted payment pages (HPP)?

**Comment by sandervanhooft** [comment]
@willemstuursma 

I interpret "white labeling" in this case as:

_every interaction between user and app, without any awareness of Mollie being the PSP._

I.e. how to white label:
- the payment screen
- registering and activating new merchant accounts
- authenticating merchants
- (future features)

**Comment by sandervanhooft** [comment]
Most of these items are already described in the docs, but fragmented.

**Comment by willemstuursma** [comment]
Ah yes. In our business white labeling usually refers to something else: becoming a PSP but outsourcing all your technology / legal / financial needs to another PSP. 

I'll look up the right term.

**Comment by sandervanhooft** [comment]
The term is currently used in the docs, so perhaps that requires some clarification as well. :)

**Comment by mollierobbert** [comment]
Thanks Sander!

By now we have a guide on how to build your own checkout: https://docs.mollie.com/payments/build-your-own-checkout

And we have a guide on white-labeling the onboarding flow: https://docs.mollie.com/oauth/onboarding

I'm spending some time improving the navigation and grouping content better as well. I'm assuming that covers the issue.

(Our apologies for responding to all of these issues this late!)
