### ISSUE TITLE
Link does no go the the correct page in Firefox and Safari

### ISSUE THREAD

**Issue by JorikMollie** [mollie/api-documentation#464]
https://github.com/mollie/api-documentation/blob/master/source/changelog/v2/changelog.rst#tuesday-21st

The link to the Get Payment endpoint dos not work in Firefox and Safari
I've added a screenshot of the pages this link redirects to.

![Screenshot 2019-06-06 at 17 00 56](https://user-images.githubusercontent.com/28565664/59108156-94426b00-893a-11e9-988f-f0d49b10ce0f.png)

**Comment by mollierobbert** [comment]
Thanks Jorik. Fixed.
