### ISSUE TITLE
Please check the cancel payment refund examples

### ISSUE THREAD

**Issue by Pimm** [mollie/api-documentation#497]
According [to the documentation][doc], this endpoint returns `204`. However, the PHP example reads:
``` php
$canceledRefund = $refund->cancel();
```
And the Python one reads:
``` python
refund = mollie_client.payment_refunds.on(payment).delete('re_4qqhO89gsT')
```

Could someone please check whether both those things are correct? They seem paradoxical.

[doc]: https://docs.mollie.com/reference/v2/refunds-api/cancel-refund

**Comment by willemstuursma** [comment]
@sandervanhooft what about the PHP example?

**Comment by sandervanhooft** [comment]
You're right @pimm, the php client is returning null upon successful cancellation.

**Comment by sandervanhooft** [comment]
[Here's the method](https://github.com/mollie/mollie-api-php/blob/5292588e62d985ad844f5af7c62606bcf8062708/src/Resources/Refund.php#L126:L141)

**Comment by sandervanhooft** [comment]
I'm a bit swamped right now, so I can either put it on my backlog or you can do the PR :).
