### ISSUE TITLE
My webhook doesn't get called

### ISSUE THREAD

**Issue by ramonvermeulen** [mollie/api-documentation#503]
When creating my payment the webhook URL does not get called on status updates.
Any clue how this can happen? I am running my webhook on a different port than normal HTTP/HTTPS traffic (port 3030), but I provide a full webhook URL with this port included.

I am using a test API key and I am able to receive a payment link and select a new payment status through the payment link, but my webhook doesn't get called. I know this because I am using a node.js remote server debugger, and my breakpoints doesn't get executed after I update the status of a payment through the payment URL. When I do a POST myself on this webhook endpoint through postman the breakpoint does get executed. The only thing I can think off is that mollie forces the webhook to be on port 80 or 443.

**Comment by ndijkstra** [comment]
Hi @ramonvermeulen, is the webhook URL public so we can call it? If it is, can you send an email to info@mollie.com with some payment ID's so we can do some more research?

**Comment by ramonvermeulen** [comment]
Yes, it is an public webhook url. The webhook should POST to `https://dev.api.examenoverzicht.nl:3030/payments/webhook`. I'll send some payment ID's with information to the provided e-mail address.

**Comment by ndijkstra** [comment]
@ramonvermeulen I get an error about the SSL certificate, so that is the problem that you don't receive our webhook calls.

**Comment by ramonvermeulen** [comment]
@ndijkstra Thanks! Checked it with https://www.sslshopper.com/ssl-checker.html#hostname=https://dev.api.examenoverzicht.nl:3030 and there are indeed things going wrong with SSL. I'll fix the certificate.
