### ISSUE TITLE
Move changelog here

### ISSUE THREAD

**Issue by willemstuursma** [mollie/api-documentation#52]

**Comment by vernondegoede** [comment]
I made some minor changes to the styling of the changelog. They're in the [`move-changelog-new-docs`](https://github.com/mollie/api-documentation/tree/move-changelog-new-docs) branch.

So far:
- Highlight correct subnavigation item;
- Aligned copy of new changelog with our [current changelog](https://www.mollie.com/en/developers/changelog);
- Position list of changes correctly. Aligned layout with our current changelog on mollie.com

@willemstuursma @Smitsel There's currently no way to switch between API versions. Is this something we would like to handle in the same way as we do in the API reference (by introducing a select box on top of the sidebar)?

**Comment by willemstuursma** [comment]
I think having one big changelog is fine. It will show users of the `v1` version compelling reasons to upgrade.

**Comment by Smitsel** [comment]
That will however limit us a bit. I can see why in the future we might have v1 legacy changes which need to be added to changelog. Might work confusing.

Think the nice way would be to add the selector switch between v1 and v2.

**Comment by willemstuursma** [comment]
That's also fine, can you set it up @vernondegoede ?

**Comment by vernondegoede** [comment]
Sure, will do.

**Comment by vernondegoede** [comment]
I'm expecting to finish this monday.

**Comment by willemstuursma** [comment]
https://docs.mollie.com/changelog/v1/changelog

@vernondegoede the dropdown shows the wrong value

**Comment by vernondegoede** [comment]
Fixed in #93.
