### ISSUE TITLE
Mollie webhook being called twice after successful payment + Proposal to stop confusing webhook calls after v2 update.

### ISSUE THREAD

**Issue by DigitalLeaves** [mollie/api-documentation#528]
Related to https://github.com/mollie/api-documentation/issues/300, after v2, I am receiving duplicate calls when a payment is made. The new statuses for payments are super confusing. When we receive a payment webhook call with a tr_xxxxxxx identifier, it's hard to understand if:

- the payment was done
- there was a refund
- there was a chargeback
- the payment was settled/paid/some intermediate paid status

I would like to explain some confusing real life scenarios and propose a change that will remove the ambiguity in Mollie webhook calls.

### Scenario 1
Two refunds for the same payment (i.e: 20 and 30 euros from a 100 euros payment).
If you issue two refunds for the same payment, for two different amounts, the same day, you will receive two calls and if you ask for the status, it will be paid. So you will have to look for refunds, chargebacks, etc... But you only get the current refund status, not an activity record.

I know I can check for the amountRefunded variable, but it's too complex to keep track of the amounts that were refunded in our backends and store them in our database, and we should not keep track of that information our side. We should be able to know 'what happened', not 'what is the current status'.

### Scenario 2
I execute a recurring automatic payment and I get two calls to the webhook. Both of them are "paid" status, and I cannot understand what is the difference between them. No chargebacks or refunds. That forces us to introduce a LOT of complexity in the backend to avoid generating duplicate invoices for the same payment to our customers. 

## So a proposal

add a "event" webhook. This way, we can get a more detailed and accurate information on why the webhook is called. Not data but activity.

I.E: ev_xxxxxxxx and then after a call to /payments/xxxxx/events/yyyyyy we can get something like:
### refund:
```{ activity: "refund", amount: {value: -20, currency: "EUR"} }```

### chargeback: 
```{ activity: "chargeback", amount: {value: -20, currency: "EUR"} }```

### status change:
```{ activity: "status_change", old: "open", new: "paid" }```

### settlement (when it's paid to a point where no more paid webhook calls are going to be made and we can deliver the invoice):
```{ activity: "payment_settled", amount: { value: 100, currency: "EUR" } }```

Happy to discuss about this idea.

**Comment by sandervanhooft** [comment]
I _completely_ agree. There are some ongoing discussions about this, last time I checked spearheaded by @vernondegoede .

**Comment by sandervanhooft** [comment]
May also be of special interest to @frankdejonge , given his ❤️ for event sourcing 😉 .

**Comment by DigitalLeaves** [comment]
Thank you very much @sandervanhooft ! I am happy to help. I have been designing APIs and working as a backend engineer for quite some time, so if I can help or offer any suggestion, feedback, or comments, I will be glad to! ☺️

**Comment by sandervanhooft** [comment]
Any news on this?

**Comment by sandervanhooft** [comment]
This is still high on my wish list for Mollie. It's hard to communicate the exact business value of this - but believe me that it is really high.

Also, I wanted to share a way that reduced the complexity a bit for me (but nearly enough):

as soon as the payment reaches status `paid`, I update the webhookUrl to an `aftercare` route with a dedicated controller. This controller now only has to detect and handle chargebacks and refunds.

That detection step is where the pain is imho: it remains incredibly complex and brittle to deduce the reason why the webhook was called exactly.

**Comment by mollierobbert** [comment]
Apologies for the radio silence from Mollie's end.

I fully agree that our webhook system has not sufficiently matured along with our product offering. It's something that we are conscious of internally, but we have not yet found the capacity to tackle it. I do expect us to make progress here in the upcoming 6-12 months, with a big disclaimer that I'm not in charge of priorities 😬 .

A good first step would be for us to offer updates on other entities than just payments. In the scenario of two refund webhooks coming in for a single payment, you would then at least get webhook calls with specific refund IDs.

Receiving the actual state that triggered the webhook is another story though. It would require a new webhook system altogether, since we currently rely on the merchant to call us in order for us to guarantee that the line is secure.

I'll link this issue internally to our webhook improvements issue.

**Comment by sandervanhooft** [comment]
Thanks @mollierobbert ! I've also discussed this issue previously with Tim Lienke (don't know his GH handle). Let me know if I can help in any way.

**Comment by lode** [comment]
> Receiving the actual state that triggered the webhook is another story though. It would require a new webhook system altogether, since we currently rely on the merchant to call us in order for us to guarantee that the line is secure.

Maybe a solution to this, since you talk about sending webhooks for other kind of entities, creating an event entity, and send webhooks for those. Then the merchant can request the event and in there will find the changes.

**Comment by DigitalLeaves** [comment]
Definitely, an event webhook is a must.

**Comment by ricovandevin** [comment]
I run into this issue now too. I have made my contact at Mollie aware of this and asked to try to get it prioritized within the development team.

**Comment by reviewingcode** [comment]
Hi, any update on this?

I hit the same wall. Trying to implement a feature where a payment refund or a chargeback would trigger some events in the app I'm working on. At the moment it is quite complex to figure out what happened.

**Comment by mollierobbert** [comment]
There is some progress: we now have an approved internal draft of what this feature should look like both in terms of the API design and the internal system design. The actual development work hasn't started yet though. That's all I can share for now, sadly.

**Comment by janwillemvd** [comment]
@mollierobbert any updates on this? 😇

**Comment by DigitalLeaves** [comment]
> @mollierobbert any updates on this? 😇

Don't expect them anytime soon. We moved to Stripe.

**Comment by mollierobbert** [comment]
We made slow but steady progress on getting this higher on the agenda.

I'll have to close this issue though, since we are closing this repository in favor of our new API documentation site. Feel free to join our Discord, where I'm sure we will announce the new webhook system once it launches.
