### ISSUE TITLE
Add a new package

### ISSUE THREAD

**Issue by VictorAvelar** [mollie/api-documentation#529]
Hi Mollie, over the past month and with the help of the OS community I've build the API wrapper for Mollie's API in golang, I will like to know which process needs to be followed in order to list it in your docs.

The source code lives here: https://github.com/VictorAvelar/mollie-api-go

**Comment by willemstuursma** [comment]
@vernondegoede could you take care of this and report back here?

**Comment by vernondegoede** [comment]
Thanks for creating the package @VictorAvelar! Much appreciated. We'll add it to https://www.mollie.com/nl/developers/packages.

Could you mail me your address details, so we can send you a small gift of appreciation? My email is vernon@mollie.com.

**Comment by VictorAvelar** [comment]
Thanks guys, email sent and well, looking forward.

**Comment by vernondegoede** [comment]
@VictorAvelar We've added the package to our "Packages & Plugins" page. Thanks again! 🙌
