### ISSUE TITLE
Remove old files from S3 bucket during deployment

### ISSUE THREAD

**Issue by mollierobbert** [mollie/api-documentation#54]
Currently a deployment just overwrites whatever files are in the S3 bucket. If we rename a file, the old file never gets removed and keeps floating around on the internet forever.

**Comment by MollieRick** [comment]
Whats the status of this?

**Comment by wvdeutekom** [comment]
@MollieRick this does not have a priority for us at the moment. @hvalle heads up ^

**Comment by mollierobbert** [comment]
It's still an issue. I renamed the following page:

https://docs.mollie.com/payments/overview

To:

https://docs.mollie.com/payments/accepting-payments

The old version of the page is still live though, with the old navigation and everything.

I tried solving this using the `reredirects` plugin for Sphinx, but it doesn't support our suffixless files yet. I created a PR for it: https://gitlab.com/documatt/sphinx-reredirects/-/merge_requests/2/diffs

Regardless of redirects, we should be able to solve this issue through a simple S3 command in the `deploy.sh` file.

**Comment by mollierobbert** [comment]
For now I forked the reredirects plugin into the repo, which gives us a way to overwrite old files with a file containing an HTML-based redirect.

**Comment by mollierobbert** [comment]
This issue resulted in issue #743.

**Comment by mollierobbert** [comment]
In 8a9c6ff I delete all the contents from the bucket before uploading the new contents to semi-fix this issue.

Of course this is less favorable than a symlink switch, since now there is a short period with every deployment where the content is unavailable. Plus, if the deployment fails half-way through, we could have complete unavailability of our API docs.

Then again, we have some CloudFront caching that we reset only at the final stage of the deployment. So maybe it will be fine. 🔥 ☕ 

During the [first deployment](https://travis-ci.com/github/mollie/api-documentation/builds/228124796) with this cleanup step in place, 369 files were deleted while 323 files were reuploaded, meaning there were over 40 stale files by now in the bucket.
