### ISSUE TITLE
Change terminology: "your customer" to "the shopper" 

### ISSUE THREAD

**Issue by willemstuursma** [mollie/api-documentation#559]
Currently we use "Your customer" for the person performing payments. It is an slightly vague term, I propose we switch to "shopper" in the documentation to make it crystal clear.

**Comment by shirshir** [comment]
Although I have used Mollie to pay for some school fees I think that shopper is a good fit for the person doing the payment.

**Comment by feyyazesat** [comment]
Is all mollie payment used in the shopping context? Or are there may be services provided by some websites using mollie payment? Shopper could be very specific to an action.

**Comment by mattijsbliek** [comment]
I think either shopper or consumer would be clear. The only drawback I see is that we have the Customers API 🤔 Up to you whether this is a problem or not.

**Comment by sandervanhooft** [comment]
When I'm paying for services instead of products I don't identify with the term "shopper" tbh.

**Comment by sandervanhooft** [comment]
Also, the person doing the shopping (shopper) doesn't have to be the person making the payment. 

@willemstuursma What vagenuess does the term customer result in?

**Comment by mollierobbert** [comment]
I think 'shopper' has a 'consumer' ring to it, which makes it more specific (and therefore less encompassing) than 'customer'.

Consider for example app or platform users, who pay for using a SaaS tool. I wouldn't consider those 'shoppers', but they are 'customers' of the app or platform.

I don't think a business-to-business retail store considers their business clients 'shoppers' either.

**Comment by sandervanhooft** [comment]
@mollierobbert thanks. So to be clear: what do you suggest?

**Comment by dafeso** [comment]
I understand why you raise this question, but I don't feel the solution lies in _replacing_ the term, more so in clarifying it, mostly for the same reasons Robbert described.

What about a directive that displays a definition on hover? Similar to the `abbr` directive used [here](https://docs.mollie.com/guides/mollie-components/overview). Mind you, it may require a different clarification depending on the context.

If it's frequently or heavily used in a guide, the term may 'just' require an introduction of sorts, e.g. [here](https://docs.mollie.com/oauth/onboarding).

**Comment by sandervanhooft** [comment]
I agree with @dafeso . Also, note that the term "Customer" is used in the API (i.e. `/customers` endpoint, `Customer` resource). Introducing another term for the customer without changing the API accordingly will probably result in more confusion, not less.

**Comment by mollierobbert** [comment]
I agree. Closing the issue.
