### ISSUE TITLE
Visual issue: overlap

### ISSUE THREAD

**Issue by sandervanhooft** [mollie/api-documentation#569]
<img width="781" alt="image" src="https://user-images.githubusercontent.com/7265703/70614206-6819e680-1c0a-11ea-81a3-e37a97409076.png">

https://docs.mollie.com/reference/v2/payments-api/create-payment

**Comment by sandervanhooft** [comment]
It's `restrictPaymentMethodsToCountry` in this case.

**Comment by willemstuursma** [comment]
@ndijkstra can we hack it by including an extra newline or something?

**Comment by ndijkstra** [comment]
It will look something like this:
![image](https://user-images.githubusercontent.com/3372841/70992772-c4797c00-20ca-11ea-9bc4-7dc3284904f2.png)

**Comment by willemstuursma** [comment]
LGTM!
