### ISSUE TITLE
Clarify webhook behaviour for refunds on order payments

### ISSUE THREAD

**Issue by SanderVanLeeuwen** [mollie/api-documentation#575]
It took me some time to figure out that partial refunds, made on an payment belonging to an order, are not reported to the webhook related to that order. It's obvious now (the order payment documentation clearly states you can provide a separate webhook for those payments), but at first I was slightly misled by the [webhooks documentation](https://docs.mollie.com/guides/webhooks) which says:

> Furthermore, the webhook will be called when:
> - The order or part of the order is refunded. 

A slight warning that 'part of the order' is considered to be one of the order lines, and not a part of the related payment, might be in place? Or maybe I just need to read more carefully next time 😅

**Comment by mollierobbert** [comment]
Sorry for the late reply. We did a poor job keeping up with the issues on this repo.

Good feedback nonetheless. I checked the docs, and by now it has a better description in the Orders API section of the webhooks documentation that clarifies that this is indeed about order line refunds.
