### ISSUE TITLE
Mollie webhook URL called but payment id not getting

### ISSUE THREAD

**Issue by jishansiddique** [mollie/api-documentation#584]
We have already created issues and this similar this [https://github.com/mollie/api-documentation/issues/583](URL) 

We have set webhook URL the id parameter in request but every time we got id is null so my question is id parameter are we pass or your side passed the parameter? let me know we are big trouble at this moment.

Create a payment response
```
{
    "resource": "payment",
    "id": "tr_pCHpdCbpb5",
    "mode": "test",
    "createdAt": "2020-01-24T09:40:18+00:00",
    "amount": {
        "value": "100.10",
        "currency": "EUR"
    },
    "description": "46-201800046",
    "method": null,
    "metadata": null,
    "status": "open",
    "isCancelable": false,
    "expiresAt": "2020-01-24T09:55:18+00:00",
    "profileId": "pfl_wv9K6uRbg7",
    "sequenceType": "oneoff",
    "redirectUrl": "http://localhost:60991/nl-nl/OrderValidation?paymentType=mollie",
    "webhookUrl": "https://devee05.solvisoft.net/api/mollie/webhook",
    "_links": {
        "self": {
            "href": "https://api.mollie.com/v2/payments/tr_pCHpdCbpb5",
            "type": "application/hal+json"
        },
        "checkout": {
            "href": "https://www.mollie.com/payscreen/select-method/pCHpdCbpb5",
            "type": "text/html"
        },
        "documentation": {
            "href": "https://docs.mollie.com/reference/v2/payments-api/create-payment",
            "type": "text/html"
        }
    }
}
```

When we paid amount specific to payment method Webhook URL automatically called but we got id every time null, but we detected or auto mapped currently created payment id? in webhook URL.

**Comment by MollieRick** [comment]
Hi,

As mentioned in your other issue, please reach out to our tech support. They can help you with setting up the webhook. You can reach them via the details on our contact page:  https://www.mollie.com/en/contact.

Have a good weekend!

**Comment by jishansiddique** [comment]
@MollieRick Thank you for quick support we have done webhook URL and got the payment id 👍

**Comment by shahmy** [comment]
@jishansiddique Please can u let me know how you got your ID via webhook URL. I tried with Laravel. Payment is done succesflly. but I cannot get ID via webhook URL to update payment status. 
I used https://github.com/mollie/mollie-api-php this..

**Comment by MollieRick** [comment]
@shahmy We send a POST request to your webhook URL with an `id` parameter. If you have questions about this, please reach out to our support team via https://www.mollie.com/en/contact.

**Comment by shahmy** [comment]
@MollieRick Thanks for your prompt response. Will contact via given URL

**Comment by jishansiddique** [comment]
@shahmy please check the below code in ASP.NET
Payment id coming in `Request.Content`
```
public virtual HttpResponseMessage Webhook(string id) {

  HttpContent requestContent = Request.Content;
  string jsonContent = requestContent.ReadAsStringAsync().Result; 
  if (!string.IsNullOrEmpty(jsonContent)) {
    id = GetPaymentId(jsonContent);   
  }
  return Request.CreateResponse(HttpStatusCode.OK);
}

public virtual string GetPaymentId(string jsonContent) {
  string paymentID = string.Empty;

  string[] jsonsString = jsonContent.Split('=');
  if (jsonsString != null && jsonsString.Length > 0) {
    paymentID = jsonsString[1];
  }

  return paymentID;
}
```

**Comment by jishansiddique** [comment]
Hi @kevinsechocho,
If you are using ASP.NET or C# you can use this code it's worked for me
Payment Id coming to the `Request.Content`
https://github.com/mollie/api-documentation/issues/584#issuecomment-811896426
