### ISSUE TITLE
Add 404 error page

### ISSUE THREAD

**Issue by Daanvm** [mollie/api-documentation#59]
A non-existing page currently returns some XML instead of a nice page telling me that this page doesn't exit.

This is the XML that is now returned for an invalid URL:

    <?xml version="1.0" encoding="UTF-8"?>
    <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>52B8ADFC3D155ADB</RequestId><HostId>M41Eg5sxx7W6+5C6WgwkirHLhEBU5xQhYHkBUwqpxhTXVKr+036+wgHYIOYbJPvegLqsmhXsSzI=</HostId></Error>

**Comment by lvgunst** [comment]
Example: https://docs.mollie.com/non-existing

**Comment by wvdeutekom** [comment]
For reference: the settings have been set in cloudfront to display a 404 page upon a 404 response. S3 does not have to be adjusted for this.
