### ISSUE TITLE
Mollie Connect overview page

### ISSUE THREAD

**Issue by sandervanhooft** [mollie/api-documentation#592]
The text at https://docs.mollie.com/oauth/overview mentions the authorization token, but it's ~missing~ abbreviated in the diagram.

![](https://assets.docs.mollie.com/_images/oauth-overview-flow@2x.png)

Also, the organization access token is mentioned in table below, but it's coming out of nowhere. I don't think this page is the right place to mention the organization access token, as it has little to do with the default OAuth flow.

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/7265703/73737444-f14d2580-4742-11ea-93d5-7064012b9335.png">

**Comment by sandervanhooft** [comment]
FOUND the Authorization code in the diagram. It's abbreviated. So either ignore my previous comment on the authorization code or write it in full.

The comment on the organization access token remains unchanged.

**Comment by willemstuursma** [comment]
Thanks @sandervanhooft , I've updated the copy on this page.
