### ISSUE TITLE
Page "Requesting Apple Pay Payment Session" rendering too wide

### ISSUE THREAD

**Issue by sandervanhooft** [mollie/api-documentation#609]
[This page](https://docs.mollie.com/reference/v2/wallets-api/request-apple-pay-payment-session) walks off my laptop screen, right side.

Tested on both Safari and Chrome, full screen. Smaller (tablet?) breakpoint seems ok.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/7265703/77762593-0d31c100-703a-11ea-9f03-59517a8abab2.png">

**Comment by mollierobbert** [comment]
This doesn't seem to be an issue anymore, or are you still experiencing it @sandervanhooft?

**Comment by sandervanhooft** [comment]
Correct!
