### ISSUE TITLE
(v1) webhook called only with status 'open' in test mode with recurring 'first' payment

### ISSUE THREAD

**Issue by jaapmurre** [mollie/api-documentation#613]
From the docs (still using v1), I gather that the webhook should never be called with status 'open'. But when I do (test mode) 'first' payments, all I get are one-time only status-'open' webhook calls, never followed by a 'paid' webhook call. 

In the Mollie Dashboard Transactions, I can see the test mode transactions as 'paid'. Is this the correct (to be expected) webhook calling behavior? Did I miss anything?

When I do non-recurring payments, the same code receives several webhook calls, most with 'paid' status. That I can use. I don't know how to handle 'open'.

**Comment by sandervanhooft** [comment]
Hi @jaapmurre,

Thanks for reporting this. It looks like a bug, Mollie’s looking into it.

**Comment by MollieRick** [comment]
Hello @jaapmurre,

Thanks for reporting. Do you maybe have a payment ID (starting with "tr_") of the **test** payment where this happened ?

**Comment by jaapmurre** [comment]
Dear Rick,

Here are some of my payments with id and status. They are always first
called with status Open and then shortly after with Paid. This is not a
problem for me but it seems to clash with the documentation where it says
that a webhook is never called with status Open.

With best wishes,

     -- Jaap

**Comment by MollieRick** [comment]
Hi Jaap,

It should not happen indeed. That's why I want to search up your payments. Can you give some IDs?

**Comment by jaapmurre** [comment]
Are these the IDs you were looking for? (In column 2 of the sheet I sent
you.) -- Jaap

tr_7DpghGRjyF
tr_7DpghGRjyF
tr_a8qTgchdPC
tr_a8qTgchdPC
tr_MeQbwUpkrR
tr_MeQbwUpkrR
tr_hAa57RaSnW
tr_hAa57RaSnW
tr_nVHjPEj5xC
tr_nVHjPEj5xC
tr_3HRGWGTvDA
tr_3HRGWGTvDA

**Comment by MollieRick** [comment]
I can not see any 'open' webhook calls regarding the payments you mentioned. We actually did not earlier got this issue. Do you have some network logs as well?

**Comment by jaapmurre** [comment]
Dear Rick,

I don't have network logs except the once in my first response, which are
database exports from the payments records that I extract from the webhook
calls (as per your example code in PHP).

The PHP code is as follows and as you can see, it directly copies all calls
to the webhook to the database.

An example of call with 'open' is:

tr_nVHjPEj5xC 5e9789db9a646 1 23 NULL 566.28 test single_yearly Netherlands
NL nl yes 21 98.28 468 open PT14M59S 0 2020-04-15T22:25:31.0Z pfl_qWapssg23r
cst_QtfcueQkF8 null first nl
tr_nVHjPEj5xC 5e9789db9a646 1 23 44 566.28 test single_yearly Netherlands NL
nl yes 21 98.28 468 ideal paid 0 2020-04-15T22:25:31.0Z
2020-04-15T22:25:38.0Z pfl_qWapssg23r cst_QtfcueQkF8 {"consumerName":"T.
TEST","consumerAccount":"NL17RABO0213698412","consumerBic":"ABNANL2A"} first
nl

I see the Mollie ID in my dashboard (test modus) with the correct order
number but my Dashboard mentions no open transactions (which makes sense as
within a very short time the status changed 'paid', resulting in a second
call). Also it was called with CODE  PT14M59S and I see these types of
codes only with 'open' calls.

I hope this helps. As I said earlier, it does not really bother me to have
a 'paid' call preceded by an 'open' call.

Groet,

     -- Jaap

    public function webhook()
    {
        try
        {
            if (!empty($_GET['testByMollie']))
            {
                die('OK'); // Active when running for real
            }

             $payment  = $this->mollie->payments->get($_POST["id"]); //
This is for real
             $order_id = $payment->metadata->order_id;

            $query = ee()->db->select('order_id,status') // webhook may be
called several times, so we must check whether this is the first time
                ->from('exp_nt_payments b')
                ->where(array(
                    'b.order_id' => $order_id, // Has an paid order already
been entered before?
                    'b.status' => 'paid'
                ))
                ->get();
            $result = $query->result_array();

            $payment_id = $this->_database_write($payment); // We record
the payment locally no matter what its current status is
                                              // This means that several
payment rows can be entered for the same order
                                              // e.g, with status 'open'
and then several 'paid' payments as Mollie keeps calling
                                              // the web hook

            if ($payment->isPaid() == TRUE && $result == FALSE) // If
payment is paid now but it wasn't earlier as $result is empty, so we take
some action
            {
                if (!$payment->metadata->team_id) {
                    $team_id =
$this->create_team($payment->metadata->users,$payment->metadata->member_id,$order_id,$payment->metadata->days);
                    ee()->db->update(
                        'exp_nt_payments',
                        array(
                            'team_id'  => $team_id
                        ),
                        array(
                            'id' => $payment_id
                        )
                    );
                }
                ee()->db->insert(
                    'exp_nt_invoices',
                    array('payment_id' => $payment_id)
                );
            }
            elseif ($payment->isOpen() == FALSE)
            {
                // The payment isn't paid and isn't open anymore. We can
assume it was aborted.
            }
        }
        catch (Mollie_API_Exception $e)
        {
            echo "API call failed: " . htmlspecialchars($e->getMessage());
        }
    }
}

**Comment by MollieRick** [comment]
Hi Jaap,

I can see that you received a webhook call because the payment was paid. Why it said that the payment was still open is a mystery. It could be a disruption in our service at that moment. 

Because I can not see any wrong webhook-calls at our end and no other merchants alerted us about this, will I close this issue for now.

I can advise you to change to the v2 API and, let us know if it happens again!

**Comment by jaapmurre** [comment]
Thanks! Will move to v2 eventually but had a bunch of old code I could
re-use. -- Jaap
