### ISSUE TITLE
Check mandatoriness of parameters in update profile

### ISSUE THREAD

**Issue by Pimm** [mollie/api-documentation#622]
[According to the docs](https://github.com/mollie/api-documentation/blob/master/source/reference/v2/profiles-api/update-profile.rst), `PATCH /profiles/*id*` has a bunch of mandatory parameters (`name`, `website`, `email`, `phone`).

As this is a `PATCH` call, I'd expect those to be optional.

**Comment by MollieRick** [comment]
Hi Pimm,

Thanks for your message. I agree with you and will dive into it.

**Comment by MollieRick** [comment]
Hi Pim,

We changed the API based on your suggestion. Thanks again and have a good weekend!
