### ISSUE TITLE
Requesting a QR Code only works when using a live api key (Mollie .NET API)

### ISSUE THREAD

**Issue by msadonis** [mollie/api-documentation#634]
I have noticed that when i requested a QR Code with a bancontact payment method, the response only contains a QR Code when i used a live api key.
Is it somehow possible to receive one when using a test api key also?

**Comment by MollieRick** [comment]
Hi @msadonis,
I'm sorry, it's not. We can not create a QR-code since the test mode payments happens outside the loop of Bancontact. You will redirected to a Mollie page to select the final state.

**Comment by MollieRick** [comment]
Hi @msadonis,

The .NET Library is maintained by our community. Please create an issue here; https://github.com/Viincenttt/MollieApi/issues
