### ISSUE TITLE
Metadata max size

### ISSUE THREAD

**Issue by LanzoVanSlooten** [mollie/api-documentation#639]
When I create a payemt request I use the use the metadata to store extra information. I will store a payment id and voucher info.

But because of the limit of 1KB, I cannot store all the info I want. 

Is it possible to make it a little bigger like 10KB?

**Comment by sandervanhooft** [comment]
+1

**Comment by sandervanhooft** [comment]
@willemstuursma ?

**Comment by MollieRick** [comment]
What is the reason you all want to stall this info with the metadata of the payment? Storing this information in your database alongs a payment ID should also be possible right?

What is the benefit here? :)

**Comment by sandervanhooft** [comment]
Hi @MollieRick ,

Here's an example from Cashier Mollie, metadata on a `first payment`.

Nothing is _not_ persisted in the db until the payment has been processed successfully at Mollie.

The payment is processed into a local order, invoice pdf etc once the webhook gets called. The metadata is then used to trigger all actions (which can be multiple, the below is the simplest example).

```php
{
  "owner": {
    "type": "Laravel\\Cashier\\Tests\\Fixtures\\User",
    "id": 1
  },
  "actions": [
    {
      "handler": "Laravel\\Cashier\\FirstPayment\\Actions\\StartSubscription",
      "description": "Monthly payment",
      "subtotal": {
        "currency": "EUR",
        "value": "10.00"
      },
      "plan": "monthly-10-1",
      "name": "default",
      "quantity": 1
    }
  ]
}
```

**Comment by sandervanhooft** [comment]
Right now the 1kb seems to be enough. But 1kb is only 1000 characters, so I think in some cases it may not be enough.

**Comment by MollieRick** [comment]
Personally I don't see the benefit of increasing it, maybe @willemstuursma does?

**Comment by LanzoVanSlooten** [comment]
The payment is not yet stored in the database. So I also add voucher info to the metadata. I could add only the voucher id's and retrieve the data from the database, But when I put it in the metadata these calls are not necessary.

This is a example when it goes wrong:

{
	"purchaseId": "3e77a588-93e6-4db7-8bc7-120f6c6a5b01",
	"readableEventId": "Online_Workshop2289556070",
	"eventName": "Flierefluiten",
	"voucher_codes": null,
	"vouchers": [
		{
			"status": "valid",
			"errorMessage": "",
			"name": "",
			"amount": 121.0,
			"amountExcl": 100.0,
			"used_amount": 0.0,
			"voucherId": "34e6c5b2-04c1-ea11-a812-000d3ab9bd1c",
			"voucherCode": "H9N3X1"
		},
		{
			"status": "valid",
			"errorMessage": "",
			"name": "",
			"amount": 60.5,
			"amountExcl": 50.0,
			"used_amount": 0.0,
			"voucherId": "31e6c5b2-04c1-ea11-a812-000d3ab9bd1c",
			"voucherCode": "W9C2L1"
		},
		{
			"status": "valid",
			"errorMessage": "",
			"name": "",
			"amount": 60.5,
			"amountExcl": 50.0,
			"used_amount": 0.0,
			"voucherId": "2ae6c5b2-04c1-ea11-a812-000d3ab9bd1c",
			"voucherCode": "X0Y6Q0"
		}
	],
	"eventid": "e5b970c9-df2b-4271-a863-519d0dd953dc",
	"total": 302.5,
	"totaltoPay": 60.5,
	"totalexcl": 50.0,
	"ConfirmationUrl": "",
	"Vestiging": "Online",
	"RegistratieSleutel": "ABCEDFG-4695-9B3A-E780-18FED990BD70"
}

**Comment by willemstuursma** [comment]
Sorry, we're not changing the size limit of metadata.

Metadata is intended to store references to entities on the merchant's end, such as an order ID et cetera.

If you can't store it with your payment, I recommend you create a dedicated entity to hold all this data and store that before creating the payment with Mollie, with metadata to point to this entity.
