### ISSUE TITLE
no suitable wrapper could be found in /home/clients/89fe28623ad6e7400fdd75eacc9b0e46/web/wp-content/plugins/mollie-payments-for-woocommerce/src/Mollie/WC/Helper/PaymentMethodsIconUrl.php on line 58

### ISSUE THREAD

**Issue by shana0780** [mollie/api-documentation#657]
After the last update, I have all this errors

Warning: file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/clients/89fe28623ad6e7400fdd75eacc9b0e46/web/wp-content/plugins/mollie-payments-for-woocommerce/src/Mollie/WC/Helper/PaymentMethodsIconUrl.php on line 58

Warning: file_get_contents(https://www.mollie.com/external/icons/payment-methods/belfius.svg): failed to open stream: no suitable wrapper could be found in /home/clients/89fe28623ad6e7400fdd75eacc9b0e46/web/wp-content/plugins/mollie-payments-for-woocommerce/src/Mollie/WC/Helper/PaymentMethodsIconUrl.php on line 58

Warning: file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/clients/89fe28623ad6e7400fdd75eacc9b0e46/web/wp-content/plugins/mollie-payments-for-woocommerce/src/Mollie/WC/Helper/PaymentMethodsIconUrl.php on line 58

Warning: file_get_contents(https://www.mollie.com/external/icons/payment-methods/creditcard.svg): failed to open stream: no suitable wrapper could be found in /home/clients/89fe28623ad6e7400fdd75eacc9b0e46/web/wp-content/plugins/mollie-payments-for-woocommerce/src/Mollie/WC/Helper/PaymentMethodsIconUrl.php on line 58

Warning: file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/clients/89fe28623ad6e7400fdd75eacc9b0e46/web/wp-content/plugins/mollie-payments-for-woocommerce/src/Mollie/WC/Helper/PaymentMethodsIconUrl.php on line 58

Warning: file_get_contents(https://www.mollie.com/external/icons/payment-methods/inghomepay.svg): failed to open stream: no suitable wrapper could be found in /home/clients/89fe28623ad6e7400fdd75eacc9b0e46/web/wp-content/plugins/mollie-payments-for-woocommerce/src/Mollie/WC/Helper/PaymentMethodsIconUrl.php on line 58

Warning: file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/clients/89fe28623ad6e7400fdd75eacc9b0e46/web/wp-content/plugins/mollie-payments-for-woocommerce/src/Mollie/WC/Helper/PaymentMethodsIconUrl.php on line 58

Warning: file_get_contents(https://www.mollie.com/external/icons/payment-methods/kbc.svg): failed to open stream: no suitable wrapper could be found in /home/clients/89fe28623ad6e7400fdd75eacc9b0e46/web/wp-content/plugins/mollie-payments-for-woocommerce/src/Mollie/WC/Helper/PaymentMethodsIconUrl.php on line 58

Warning: file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/clients/89fe28623ad6e7400fdd75eacc9b0e46/web/wp-content/plugins/mollie-payments-for-woocommerce/src/Mollie/WC/Helper/PaymentMethodsIconUrl.php on line 58

Warning: file_get_contents(https://www.mollie.com/external/icons/payment-methods/bancontact.svg): failed to open stream: no suitable wrapper could be found in /home/clients/89fe28623ad6e7400fdd75eacc9b0e46/web/wp-content/plugins/mollie-payments-for-woocommerce/src/Mollie/WC/Helper/PaymentMethodsIconUrl.php on line 58

Warning: file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/clients/89fe28623ad6e7400fdd75eacc9b0e46/web/wp-content/plugins/mollie-payments-for-woocommerce/src/Mollie/WC/Helper/PaymentMethodsIconUrl.php on line 58

Warning: file_get_contents(https://www.mollie.com/external/icons/payment-methods/sofort.svg): failed to open stream: no suitable wrapper could be found in /home/clients/89fe28623ad6e7400fdd75eacc9b0e46/web/wp-content/plugins/mollie-payments-for-woocommerce/src/Mollie/WC/Helper/PaymentMethodsIconUrl.php on line 58

Warning: file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/clients/89fe28623ad6e7400fdd75eacc9b0e46/web/wp-content/plugins/mollie-payments-for-woocommerce/src/Mollie/WC/Helper/PaymentMethodsIconUrl.php on line 58

Warning: file_get_contents(https://www.mollie.com/external/icons/payment-methods/sofort.svg): failed to open stream: no suitable wrapper could be found in /home/clients/89fe28623ad6e7400fdd75eacc9b0e46/web/wp-content/plugins/mollie-payments-for-woocommerce/src/Mollie/WC/Helper/PaymentMethodsIconUrl.php on line 58

**Comment by MollieRick** [comment]
Hi @shana0780,

This issue is about the WooCommerce plugin. Please report your issue here: https://github.com/mollie/WooCommerce.
