### ISSUE TITLE
Property nextPaymentDate (on Subscription object) not found

### ISSUE THREAD

**Issue by FoxDie12x** [mollie/api-documentation#660]
Currently, the Mollie API does not have the property nextPaymentDate on a Subscription Object if the subscription is in state 'canceled'.

Current situation:
- Calling this property on an instance of a Subscription class, does return the next payment date, but *only* if the subscription is active (i.e., not canceled).
- Calling this property on a canceled subscription will result in an error, since the subscription object will not have this property.
- Assuming a subscription is active and one calls subscriptionObj.nextPaymentDate (which will contain the value of the next payment date), due to lack (?) of documentation in the API/code, the IDE does *not* find this property on the subscription object.

I'm using PHPStorm, and this consideres the mollie PHP API library, for what it's worth (although I'm sure it also holds for the API tailored to other languages)

My proposed solution (if possible):
- could the subscription class get a nextPaymentDate property, which would default to Null (or an empty string) if the subscription were to be canceled?

Thnx!

**Comment by MollieRick** [comment]
Hi @FoxDie12x ,

Thanks for your proposal. We have some other dates in the API that we omit if there is not value, like in the Payments API with `failedAt`, `canceledAt`, etc.

If you think that there is a change needed in our API client, please file an issue there or open a pull request in the correct repo: https://github.com/mollie/mollie-api-php

Enjoy your weekend!
