### ISSUE TITLE
Sending tr_id as parameter to the redirectUrl.

### ISSUE THREAD

**Issue by JatGitHub** [mollie/api-documentation#664]
Hi,

I would like to be able to add, or have added, the id of the transaction (tr_id) to the redirectUrl.
This would enable to access the metadata, without any action on my side.
Now I have to store the create orderId, together with tr_id in a database, to be able to find it when the redrictUrl is called.

Thank,

**Comment by robindirksen1** [comment]
@JatGitHub have you thought about storing the transaction id in the session?

**Comment by ndijkstra** [comment]
You could, after creating the payment, update the payment with a new `redirectUrl` that includes the Transaction ID. https://docs.mollie.com/reference/v2/payments-api/update-payment

**Comment by JatGitHub** [comment]
@ndijkstra Thanks. Do you know if update-payment is in the PhP package?

**Comment by ndijkstra** [comment]
@JatGitHub Yes it is. You can find an example here: https://docs.mollie.com/reference/v2/payments-api/update-payment#example

**Comment by JatGitHub** [comment]
@ndijkstra  Great, thanks!
