### ISSUE TITLE
PayPal: open a new account give a 404 error

### ISSUE THREAD

**Issue by JatGitHub** [mollie/api-documentation#667]
Hi, 

When processing a payment requesting USD, my user is diverted to PayPal.
If then the button create an account is pressed, they land on this error page:

https://www.mollie.com/en/webapps/hermes?token=EC-30U266029B350724D&country.x=BE&locale.x=nl_NL&ulOnboardRedirect=true

Please advise.
Jeroen

**Comment by MollieRick** [comment]
Hi @JatGitHub,

Thanks for the report.
We will investigate this and come back to you shortly.

**Comment by MollieRick** [comment]
@JatGitHub Hmm, I can not reproduce this behaviour. Do you maybe have a screen recording and a payment ID for me?

**Comment by JatGitHub** [comment]
Follow this link:
https://divinefulness.info/mollie/f/starter.php?p=75.00&d=Your%20saboteur%20resolved&a=c&c=USD
then push this button:
![afbeelding](https://user-images.githubusercontent.com/9821114/94159689-1f26dc00-fe84-11ea-8049-c361a775e19e.png)

**Comment by MollieRick** [comment]
What do you do with the `checkout` url? The url in the browser is not what we pass via the API.
