### ISSUE TITLE
Is the webhook called if we use the cancel API ?

### ISSUE THREAD

**Issue by adelinmaubray** [mollie/api-documentation#674]
Hi everyone, 

I have a question about the cancel payment API
https://docs.mollie.com/reference/v2/payments-api/cancel-payment

I'm wondering if the webhook is called after we call this API or if I have to handle the cancellation in another than my webhook ?

In my case, I delete a reservation if a payment is cancelled, expired or failed.  It is done when my webhook is called.  
So I just would like to know if I need to add code to do the same thing if I cancel the payment by myself ?

Thank you so much for your response :)

**Comment by willemstuursma** [comment]
Yes, the webhook will be called when you cancel the Payment via the Cancel Payment API.

**Comment by adelinmaubray** [comment]
Thanks you so much for your answer 😁
Have a lovely day
