### ISSUE TITLE
How to make a payment cancellable ?

### ISSUE THREAD

**Issue by adelinmaubray** [mollie/api-documentation#675]
Hi everyone !

I would like to cancel a payment using the cancel API
https://docs.mollie.com/reference/v2/payments-api/cancel-payment

But when a call the API, a have an error because the payments are not cancellable ('isCancelable' = false)

So I would like to know how to make it true to be able to cancel payment when its status is 'open' ?

Thanks you so much

**Comment by willemstuursma** [comment]
Hi @adelinmaubray. Only bank transfer and direct debit payments can be canceled while open.
