### ISSUE TITLE
[proposal][test_environment][payment/order api]: add a field to force a payment result in test mode

### ISSUE THREAD

**Issue by nathanschwarz** [mollie/api-documentation#690]
I'd like to suggest an improvement to the current api in test mode : 

It would be great to add an optional field for the `payment.create` and `order.create` queries in `testmode` to be able to force the order / payment status to : `paid, pending, authorized, expired, canceled`.

It would simplify the creation of unit tests and avoid the use of mockups during development.

**Comment by MollieRick** [comment]
Hi @nathanschwarz,

Thanks for your suggestion! 

Unfortunately I have to disappoint you, we are not going to make this in our API. We want to simulate the 'real live' flow via test mode. This means that the payment will never go directly to another status than `open` and `pending` and that the consumer needs to be redirected. I recommend you to mock your API calls to Mollie.

If you have any questions, do not hesitate to contact us via our support department.

Cheers,
Rick
