### ISSUE TITLE
Integrating with modern frontend frameworks

### ISSUE THREAD

**Issue by octalpixel** [mollie/api-documentation#692]
Hi,
There is very limited documentation in using Mollie with modern frameworks. Probably more examples of using them would be really great.

Cheers!

**Comment by MollieRick** [comment]
Hi @octalpixel ,

Feel free to create some example and to open a pull request for it. :-)

Cheers,
Rick

**Comment by willemstuursma** [comment]
cc @Marinolinderhof @el-angel
