### ISSUE TITLE
Table on Multi currency isn't correctly styled on Mobile 

### ISSUE THREAD

**Issue by Marinolinderhof** [mollie/api-documentation#72]
On Mobile devices the url `docs.mollie.com/guides/multicurrency.html`  has a table. This isn't styled correctly.  I made a first try by removing the heading and used some flexbox to style it more like it should. the problem is that the decimal number makes no sense without a header.  We could remove it or add a title before the number. But then i need or `data-attribute` per `<tr>` like `<tr data-title="{decimal-tilte}">` or a span that we can hide via media-queries. 

![screen shot 2018-05-09 at 17 42 46](https://user-images.githubusercontent.com/3657762/39824767-6dc6e52a-53b0-11e8-8d74-c17b64f0506b.png)

**Comment by MollieRick** [comment]
@mattijsbliek Do you have time to take a look at this?

**Comment by mattijsbliek** [comment]
I probably have some time this week or the next, do you need it done before a certain date?

**Comment by mattijsbliek** [comment]
Found this lingering on my todo list, it’s fixed now!
