### ISSUE TITLE
Refund webhook not happening on 'refunded' status

### ISSUE THREAD

**Issue by lode** [mollie/api-documentation#722]
When making a refund we don't get enough webhooks for the different statuses.

Shortly after sending requesting the refund we get a webhook, the status of the refund is then `processing`. A few days later a final status is reached either `refunded` or `failed`. However, we only get a webhook for the failed case, not for the success case.

We've traditionally treated `processing` as a success status since the documentation stated it can't be revoked anymore anyway. However, internally we treat a success status as a final status, and this is not possible if we later can get a `failed` status.

So we wanted to change our internal logic for `processing` as a pending status is not a final one. However, that would leave most of our refunds in a pending status as no second webhook is sent once the refund reaches the `refunded` status. To solve that we would need to poll the API every now and then to see if the status changed. This doesn't feel like the right solution.

Can you add a webhook for when a refund changes from `processing` to `refunded`?

**Comment by ndijkstra** [comment]
Hi @lode, we are sending a payment webhook when the status of the payment will change to "refunded". In this case, the refund status is "refunded". We do not have webhooks for refunds specifically at the moment.

**Comment by lode** [comment]
That is not our experience.

We've received a webhook. When checking the refunds at that moment the status was `processing`. Two days later we received another webhook. And then the refund status was `failed`. In both cases the payment status was `paid` (since it was a partial refund?).

I can send you ids and timestamps and API responses we got if you want?
