### ISSUE TITLE
Missing documentation for balance API

### ISSUE THREAD

**Issue by robindirksen1** [mollie/api-documentation#723]
It looks like some of the documentation for the Mollie API is (still) undocumented.

For example, this endpoint: https://api.mollie.com/v2/balances/default. It refers to the documentation (https://docs.mollie.com/reference/v2/balances-api/get-default-balance). 

```json
{
    "resource": "balance",
    "id": "XXXXXX",
    "mode": "live",
    "createdAt": "xxxx-xx-xxTxx:xx:xx+00:00",
    "type": "default",
    "currency": "EUR",
    "description": "",
    "status": "XXXXXX",
    "availableAmount": {
        "value": "xxx.xx",
        "currency": "EUR"
    },
    "incomingAmount": {
        "value": "xxx.xx",
        "currency": "EUR"
    },
    "outgoingAmount": {
        "value": "xxx.xx",
        "currency": "EUR"
    },
    "transferFrequency": "twice-a-month",
    "transferThreshold": {
        "value": "xxx.xx",
        "currency": "EUR"
    },
    "transferDestination": {
        "type": "bank-account",
        "beneficiaryName": "XXXXXX",
        "bankAccount": "XXXXXX"
    },
    "_links": {
        "self": {
            "href": "https://api.mollie.com/v2/balances/bal_XXXXXX",
            "type": "application/hal+json"
        },
        "documentation": {
            "href": "https://docs.mollie.com/reference/v2/balances-api/get-default-balance",
            "type": "text/html"
        }
    }
}
```

Any reason why this API is available but not documented?

**Comment by robindirksen1** [comment]
@leonardogcsoares any news for this issue?

The reason why I got to this API endpoint:
I was looking for an API for listing all `balance transactions`. Like the one visible on the dashboard via the internal API (https://www.mollie.com/dashboard/org_******/administration) which list the `balance_transactions`-resource.

**Comment by leonardogcsoares** [comment]
Hey @robindirksen1.

Unfortunately we have no API currently available that would allow for the listing of balance transactions. Some API's like the above are accessible through the dashboard and going through testing with beta merchants before release, so they will not be documented.

Maybe something like the https://docs.mollie.com/reference/v2/settlements-api/get-settlement could help bridge your information needs?

**Comment by robindirksen1** [comment]
@leonardogcsoares no, sorry. That's not what I need. Thanks for the help!

If possible, could you add it as a feature request to add a `balance_transactions` API?

**Comment by leonardogcsoares** [comment]
No worries, sorry it took a little bit. I'll make sure to pass the request on internally!
