### ISSUE TITLE
Get rid of duplicate and unwanted compiled files

### ISSUE THREAD

**Issue by mattijsbliek** [mollie/api-documentation#74]
If I’m not mistaken, `source/_static` should only contain static files. However, this directory also includes the compiled CSS and JS. This is probably a bug?

Also, in the build directory the compiled files appear both in `build/_static` as well as `build/html/_static`. A single directory should be sufficient right?

**Comment by mollierobbert** [comment]
Note only specific directories are being synced to S3 with the recent changes to the deploy script.

**Comment by mattijsbliek** [comment]
Still I would argue it’s confusing DX and we should get rid of them :)

**Comment by vernondegoede** [comment]
Related: https://github.com/mollie/api-documentation/pull/119#issuecomment-401771568

**Comment by mollierobbert** [comment]
Where else should we put the compiled CSS and JS?

You saw two folder structures because the dev build outputs in `build`, while the prod build outputs in `build/html`. Normally you only get one of the two structures.

**Comment by mattijsbliek** [comment]
Ideally not in Git at all, but generated in the pipeline and uploaded to S3 directly. For local development we could do a `.tmp` directory or something that's in `.gitignore`. But at the very least I would differentiate between files that are used as is (static) and files that are compiled.

**Comment by mollierobbert** [comment]
Ah, I understand your original question better now.

I think somebody already solved this along the way then. The JS and CSS files are nowadays indeed generated in the build and uploaded to `static.docs.mollie.com`.

I'll close the issue.
