### ISSUE TITLE
Create order and customer with email including german umlaut like ä, ü, ö return 500 error

### ISSUE THREAD

**Issue by cpuell** [mollie/api-documentation#759]
Currently we see that using an email with either one of the german umlaut included will return 500 error.

Technically it should be possible to use umlaut or? Our Customers could have email like this.

**Comment by mollierobbert** [comment]
Hi cpuell, good catch. We base our email validation on the [international standard RC 5322](https://en.wikipedia.org/wiki/Email_address#Internationalization), so diacritics and non-Latin alphabets are not supported.

There is a newer standard, RFC 6532, which does support non-Latin email addresses. Not all email providers support it yet, and therefore it's quite rare to see these in the wild.

You are technically correct though, consumers could have these email addresses and we should update our validation to support RFC 6532. I'm not sure if other merchants run into this problem often, but I'll pass this suggestion on to the team internally.

For now, you can also solve this by converting the email address to 'punycode' notation.

CC @rosstuck

**Comment by mollierobbert** [comment]
Since this is a product improvement suggestion and not an API documentation issue, I'll close the issue.
