### ISSUE TITLE
Mollie payment in Opencart.

### ISSUE THREAD

**Issue by youri13pixels** [mollie/api-documentation#773]
We are using Mollie payment in Opencart.

Now we want to use Create Payment Link for our customers to allow them pay later.

Can we get Example of Create Payment Link using API in PHP (Opencart is based on PHP language.)

We wish we can get a demo , how API call and response for Create link.

Can anyone help?

**Comment by sandervanhooft** [comment]
I'm working on a PR with PHP examples [here](https://github.com/mollie/api-documentation/pull/774)

**Comment by sandervanhooft** [comment]
Also note that I just released an update to the php client to support this

https://github.com/mollie/mollie-api-php/releases/tag/v2.36.0

**Comment by youri13pixels** [comment]
Perfect! Thanks for your reply!

**Comment by sandervanhooft** [comment]
No problem. Note that PaymentLinks is in the process of being rolled out. That means it's not available to all merchant countries yet.

**Comment by sandervanhooft** [comment]
To moderator: this issue can be closed.
