### ISSUE TITLE
add a subscription button/option to the changelog

### ISSUE THREAD

**Issue by EdouardBayon** [mollie/api-documentation#775]
I would like to subscribe to the **changelog** page of the [Mollie APi docs](https://docs.mollie.com/changelog/v2/changelog)

**Comment by MollieRick** [comment]
Nice suggestion @EdouardBayon! :-)

**Comment by sandervanhooft** [comment]
Yes please!

**Comment by mollierobbert** [comment]
We now offer an RSS feed: https://docs.mollie.com/changelog.rss
