### ISSUE TITLE
Max lengths of parameters

### ISSUE THREAD

**Issue by sjongejan** [mollie/api-documentation#782]
The max length of the parameters are missing in the documentation.

For example when creating a payment its unknown how long a description can be;
https://docs.mollie.com/reference/v2/payments-api/create-payment

**Comment by MollieRick** [comment]
Hey @sjongejan,

Thanks! Good point, I will see what I can find and add.

**Comment by MollieRick** [comment]
@sjongejan I added some more info about lengths. Thanks again for suggesting.
