### ISSUE TITLE
Add payment routes endpoint page

### ISSUE THREAD

**Issue by sandervanhooft** [mollie/api-documentation#800]
The payment routes endpoint is mentioned in the routed payments guide, but documentation for this specific endpoint is missing from the API v2 reference.

The payment routes endpoint is still in private beta but I don't think that should hold us back from documenting it. It's used for updating routed payment release dates.

**Comment by mollierobbert** [comment]
It is now part of the Payments API documentation. More endpoints related to routing will go into beta soon... ⌛
