### ISSUE TITLE
Updating to docutils 0.18 breaks the build

### ISSUE THREAD

**Issue by mvdpanne** [mollie/api-documentation#817]
We currently do not pin the version of the `docutils` package (as part of `requirements.txt`). As a result, on each build we will install the latest version of the package.

On 26-10-2021, version 0.18 was released. As a result, the build of #816 started failing (see [here](https://app.travis-ci.com/github/mollie/api-documentation/builds/240606921)). The specific error is the following:
```
Exception occurred:
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/sphinx/util/nodes.py", line 94, in apply_source_workaround
    for classifier in reversed(node.parent.traverse(nodes.classifier)):
TypeError: 'generator' object is not reversible
```

For now, I've pinned the version of `docutils` to `0.17.1` as part of #818. Eventually we should figure out what the root cause of this is, and fix it.

**Comment by MollieRick** [comment]
@mvdpanne Can this be closed? :-)

**Comment by mvdpanne** [comment]
If we're okay with staying on version `0.17.1` of the `docutils` package long-term, then yes.

**Comment by mollierobbert** [comment]
Closed the issue since we are moving away from this stack entirely.
