### ISSUE TITLE
Need info about webhooks for payment links

### ISSUE THREAD

**Issue by DocBouCou** [mollie/api-documentation#843]
Hi,

Currently in the docs there are no info about what is actually sent for webhooks for payment_links. Do we get a payment_id? a payment_link_id? Something else?

**Comment by sandervanhooft** [comment]
Hi @DocBouCou ,

I went over the docs and to my surprise you're right! 💯

For now: the webhook url behaviour on PaymentLinks is the same as for Payments. So it will be called on status changes using POST as method and it will include a Payment id starting with `tr_`.

**Comment by sandervanhooft** [comment]
Regarding the documentation, this possibly impacts:

- https://docs.mollie.com/overview/webhooks ([source](https://github.com/mollie/api-documentation/blob/master/source/overview/webhooks.rst))
- https://docs.mollie.com/payments/accepting-payments ([source](https://github.com/mollie/api-documentation/blob/master/source/payments/accepting-payments.rst))
- https://docs.mollie.com/reference/v2/payment-links-api/overview ([source](https://github.com/mollie/api-documentation/blob/master/source/reference/v2/payment-links-api/overview.rst))

**Comment by DocBouCou** [comment]
Thank you for your answer, and for checking with Mollie support.

**Comment by DocBouCou** [comment]
Hi again,

I am moving forward with my coding, and I just noticed another issue in the docs regarding payment links.

I plan to use payment links with mollie connect, I just got this error: `Not all required permissions (payment-links.write) for accessing this resource were granted`.
I checked the docs, I did not find anything about payment-links permissions with oAuth and mollie connect.

**Comment by JorikMollie** [comment]
@DocBouCou Thanks for the feedback! I'll update the documentation.

**Comment by mollierobbert** [comment]
Assuming this 'solved', since we made some documentation updates back then.
