### ISSUE TITLE
Order line shipping_fee not used, update documentation.

### ISSUE THREAD

**Issue by jwaes** [mollie/api-documentation#859]
https://docs.mollie.com/reference/v2/orders-api/create-order
Sets out that orderlines have an optional parameter `type` with possible values like `shipping_fee`.
When passing that parameter it is ignored.

According to mollie helpdesk 'Pierre' (ticket `1285495`) quote:

> Our Order API is built around Klarna and due to this, shipping fee are part of the order lines. This is the default behavior and it cannot be modified.
>  
> To avoid any issue with the status of your orders, we invite you to use the option "Ship All" and ship the order instead of shipping individual order lines.

Please update the documentation to reflect the behavior we should expect.
In this case it seems 'logical', one is not supposed to 'ship' orderlines with types other than 'physical' to mark the whole order as shipped.

A version released API documentation should not contain parameters that are not used without clearly setting this out.

**Comment by mollierobbert** [comment]
Thanks for the feedback Jaco. We will sunset the Shipments API in the next year or so in favor of the new Captures API. The problem you highlighted here is definitely one of the inconsistencies that we hope to solve with the new API.
