### ISSUE TITLE
Add Swagger/OpenAPI to the documentation to ease implementation by code generation

### ISSUE THREAD

**Issue by PatrickHofman** [mollie/api-documentation#904]
I would suggest to generate a Swagger/[OpenAPI ](https://www.openapis.org/) documentation page that can be used to automatically generate software components based on the definition provided.

Since there already seems to be a structured way of generating the documentation, it might be possible to generate the Swagger/OpenAPI using the technical definition already present.

**Comment by mdocter** [comment]
So there is a Postman collection which can be found here:

https://docs.mollie.com/overview/postman-collection

And [this page from Postman](https://www.postman.com/postman/workspace/postman-open-technologies-convert-postman-collections-into-openapi/overview) points out two different tools to convert a Postman collection to OpenAPI format. But I did not test them yet, so I don't know how good they are and if they work...

**Comment by mollierobbert** [comment]
We have OpenAPI specs now. We will share them soon on the new docs website! 👀
