### ISSUE TITLE
Subscription Payment is missing MetaData

### ISSUE THREAD

**Issue by bennibau** [mollie/api-documentation#908]
**Steps to reproduce:**
- Create a Mollie Subscription with a valid mandata and payment meta data
- wait for the subscription webhook to be called

**Expected Result:**
- The payment behind the payment id in the webhook has the same meta data as the subscription which was responsible for creating that payment

**Actual Result:**
- MetaData is null

**The Documentation States:**

> We will call your webhook as usual for these payments. The only difference is, the payment ID will not be known by your system yet when we call the webhook to report the payment’s status.

This is not true since the payment does not contain the meta data that was sent when creating the payment. For us this requires now another request to retrieve the subscription meta data.

**Comment by mollierobbert** [comment]
Hi bennibau, sorry for the late reply. This GitHub repository is not well-maintained and we will be removing it soon accordingly, in favor of Discord and our new documentation site.

In any case, the Subscriptions API indeed currently does not pass on the metadata to the underlying payments. This is as intended, but, I think you make a great point that it would be useful to pass the metadata along.

I shared this improvement idea with the team that owns the Subscriptions API. Thanks!
