### ISSUE TITLE
[Question] - Balances API - List primary balance transactions context object is inconsistent with the documentation

### ISSUE THREAD

**Issue by VictorAvelar** [mollie/api-documentation#959]
## Context

I look after a Go library that helps people interact with Mollie's API. Someone ran into a problem when trying to read balance transactions because of a decoding error.

## Description

Error thrown.

```
Failed to retrieve balances: json: cannot unmarshal array into Go struct field BalanceTransaction._embedded.balance_transactions.context of type mollie.ContextValues exit status 1
```

In the documentation, the `context` field for Balance transactions is described as an object. However, when this `context` is empty, instead of being an empty object, the value turns out to be an empty array.

### Example payload

```json
{
  "resource": "balance_transactions",
  "id": "baltr_xxxxxxxxxx",
  "type": "payment",
  "resultAmount": {
      "value": "103.27",
      "currency": "EUR"
  },
  "initialAmount": {
      "value": "104.80",
      "currency": "EUR"
  },
  "deductions": {
      "value": "-1.53",
      "currency": "EUR"
  },
  "createdAt": "2022-12-23T00:00:00+00:00",
  "context": {
      "paymentId": "tr_xxxxxxxx"
  }
},
{
  "resource": "balance_transactions",
  "id": "baltr_xxxxxxxxxx",
  "type": "balance-correction",
  "resultAmount": {
      "value": "-74.74",
      "currency": "EUR"
  },
  "initialAmount": {
      "value": "-74.74",
      "currency": "EUR"
  },
  "createdAt": "2022-12-23T00:00:00+00:00",
  "context": []
},
```

I'm curious if this behavior is intentional. In PHP, the `context` gets parsed into an stdClass, but in Go, the typing system is stricter, causing the payload to trigger an error.

If this is indeed the intended behavior, it might be a good idea to update the documentation to clarify this difference. However, if this behavior isn't supposed to happen, could you kindly direct me to the appropriate place for reporting a bug? 😄

## Additional links and resources

- Original issue: https://github.com/VictorAvelar/mollie-api-go/issues/251
- Documentation page: https://docs.mollie.com/reference/v2/balances-api/list-balance-transactions

Thanks in advance 🖖🏽

**Comment by mollierobbert** [comment]
Nice find, Victor. This was unintentional indeed. We'll merge a fix for this tomorrow.
