### ISSUE TITLE
QR Code improvements on test environment + docs

### ISSUE THREAD

**Issue by mathieumagalhaes** [mollie/api-documentation#977]
# QR Code documentation needs clarification.

After testing on both `live` and `test` environments with `include: 'details.qrCode'` :
- Without method ❌ 
- With PaymentMethod.bancontact method ✅ 
- With PaymentMethod.banktransfer ✅ 
- With both PaymentMethod.banktransfer and PaymentMethod.bancontact methods ❌ 

## I came to the conclusion that you need to specify:
- Exactly ONE method. (compatible with QR Codes ofcourse)
- And be on a live key. (On test keys details is undefined)

**This is absolutely not clear from the current documentation.**

ℹ️ I suggest clarifying this in the documentation

---
# QR Code in test environment.

While using the test environment with a test API Key:
ℹ️ I would at least provide a qrCode object in the response, even a simple/fake QR Code if needed.
That way, written code can be tested.

**Comment by fjbender** [comment]
I took the liberty of moving your issue to the mollie/api-documentation repository, as it's primarily about the documentation.

I have provided clarification that exactly one `method` is required in #978.

In

https://github.com/mollie/api-documentation/blob/3ec19bae43dec194595a8526883b899b58d70747/source/payments/qr-codes.rst?plain=1#L43-L45

we clarify already that for test mode only iDeal QR codes are supported.

Could you raise your request on improving QR code returns for test mode with other `method`s in the Feature Request channel on [our Discord](https://discord.gg/mollie)?

**Comment by mathieumagalhaes** [comment]
Great! I must have read over that note.
I also raised the feature request on Discord. 👍
